In [5]:
import pandas as pd

In [6]:
df =pd.read_csv("../01-Feature-Scaling/datasets/placement_data.csv")

In [7]:
df.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

Storing the column of output and Rest will become the input :

In [8]:
X = df.drop('salary', axis=1) #axis = 1 for columns, axis = 0 for rows
y = df['salary']

INPUTS:

In [9]:
X

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed

In [10]:
y

0      270000.0
1      200000.0
2      250000.0
3           NaN
4      425000.0
         ...
210    400000.0
211    275000.0
212    295000.0
213    204000.0
214         NaN
Name: salary, Length: 215, dtype: float64

TRAIN TEST SPLIT

In [11]:
from sklearn.model_selection import train_test_split # from model selection import train_test_split

In [12]:
train_test_split(X, y, test_size=0.2, random_state=42) # X = input, y = output, test_size = 0.2 means 20% of data will be used for testing, random_state = 42 means the data will be split in a random way but it will be same every time we run the code.

[     sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
 93      94      M  52.00  Central   62.0  Central  Commerce      54.0
 84      85      M  70.00  Central   63.0   Others   Science      70.0
 95      96      M  73.00  Central   78.0   Others  Commerce      65.0
 137    138      M  67.00   Others   63.0  Central  Commerce      72.0
 210    211      M  80.60   Others   82.0   Others  Commerce      77.6
 ..     ...    ...    ...      ...    ...      ...       ...       ...
 106    107      M  61.08   Others   50.0   Others   Science      54.0
 14      15      M  62.00  Central   47.0  Central  Commerce      50.0
 92      93      F  60.23  Central   69.0  Central   Science      66.0
 179    180      F  77.80  Central   64.0  Central   Science      64.2
 102    103      F  77.00   Others   61.0   Others  Commerce      68.0

       degree_t workex  etest_p specialisation  mba_p      status
 93   Comm&Mgmt     No    72.00         Mkt&HR  55.41  Not Placed
 84    Sci&Tech    Yes    55.00        Mkt&Fin  62.00      Placed
 95   Comm&Mgmt    Yes    95.46        Mkt&Fin  62.16      Placed
 137  Comm&Mgmt     No    56.00         Mkt&HR  60.41      Placed
 210  Comm&Mgmt     No    91.00        Mkt&Fin  74.49      Placed
 ..         ...    ...      ...            ...    ...         ...
 106   Sci&Tech     No    71.00        Mkt&Fin  65.69  Not Placed
 14   Comm&Mgmt     No    76.00         Mkt&HR  54.96  Not Placed
 92   Comm&Mgmt     No    72.00        Mkt&Fin  59.47      Placed
 179   Sci&Tech     No    75.50         Mkt&HR  72.14  Not Placed
 102  Comm&Mgmt    Yes    57.50        Mkt&Fin  61.31      Placed

 [172 rows x 14 columns],
      sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
 200    201      M  69.00   Others  60.00   Others  Commerce     65.00
 212    213      M  67.00   Others  67.00   Others  Commerce     73.00
 138    139      F  82.00   Others  64.00   Others   Science     73.00
 176    177      F  59.00  Central  60.00   Others  Commerce     56.00
 15      16      F  65.00  Central  75.00  Central  Commerce     69.00
 111    112      M  51.00   Others  54.00   Others   Science     61.00
 168    169      F  48.00  Central  51.00  Central  Commerce     58.00
 73      74      M  64.60  Central  83.83   Others  Commerce     71.72
 204    205      F  74.00   Others  73.00   Others  Commerce     73.00
 139    140      M  77.00  Central  70.00  Central  Commerce     59.00
 158    159      M  67.00   Others  63.00   Others   Science     64.00
 30      31      F  64.00  Central  73.50  Central  Commerce     73.00
 186    187      F  52.00  Central  64.00  Central  Commerce     61.00
 9       10      M  58.00  Central  70.00  Central  Commerce     61.00
 67      68      M  80.92   Others  78.50   Others  Commerce     67.00
 175    176      M  63.00   Others  62.00   Others   Science     65.00
 171    172      M  80.00   Others  80.00   Others  Commerce     72.00
 18      19      F  63.00  Central  66.00  Central  Commerce     64.00
 153    154      M  49.00   Others  59.00   Others   Science     65.00
 66      67      M  83.00   Others  74.00   Others   Science     66.00
 185    186      F  88.00  Central  72.00  Central   Science     78.00
 142    143      M  85.00  Central  60.00   Others   Science     73.43
 79      80      F  69.00  Central  62.00  Central   Science     66.00
 25      26      F  52.58   Others  54.60  Central  Commerce     50.20
 104    105      M  69.00  Central  63.00   Others   Science     65.00
 145    146      M  89.40   Others  65.66   Others   Science     71.25
 189    190      F  54.00  Central  77.60   Others  Commerce     69.20
 16      17      M  63.00  Central  66.20  Central  Commerce     65.60
 45      46      F  76.00  Central  64.00  Central   Science     72.00
 150    151      M  71.00  Central  58.66  Central   Science     58.00
 108    109      M  61.00  Central  82.00  Central  Commerce     69.00
 55      56      M  60.40  Central  66.60   Others   Science     65.00
 112    113      M  58.00   Others  61.00   Others  Commerce     61.00
 191    192      M  67.00   Others  61.00  Central   Science     72.00
 124    125      M  67.00  Central  71.00  Central   Science     64.33
 128    129      M  80.40  Central  73.40  Central   Science     77.72
 75      76      F  59.00  Central  62.00   Others  Commerce     77.50
 135    136      F  72.00  Central  56.00   Others   Science     69.00
 118    119      M  76.00  Central  80.00  Central   Science     78.00
 98      99      F  69.00  Central  73.00  Central  Commerce     65.00
 96      97      F  76.00  Central  70.00  Central   Science     76.00
 183    184      M  65.00  Central  77.00  Central  Commerce     69.00
 117    118      M  77.00   Others  75.00   Others   Science     73.00

       degree_t workex  etest_p specialisation  mba_p      status
 200  Comm&Mgmt     No    87.55        Mkt&Fin  52.81      Placed
 212  Comm&Mgmt    Yes    59.00        Mkt&Fin  69.72      Placed
 138   Sci&Tech    Yes    96.00        Mkt&Fin  71.77      Placed
 176  Comm&Mgmt     No    55.00         Mkt&HR  57.90      Placed
 15   Comm&Mgmt    Yes    72.00        Mkt&Fin  64.66      Placed
 111   Sci&Tech     No    60.00         Mkt&HR  60.64  Not Placed
 168  Comm&Mgmt    Yes    60.00         Mkt&HR  58.79  Not Placed
 73   Comm&Mgmt     No    86.00        Mkt&Fin  59.75      Placed
 204  Comm&Mgmt    Yes    80.00        Mkt&Fin  67.69      Placed
 139  Comm&Mgmt    Yes    58.00        Mkt&Fin  54.43      Placed
 158   Sci&Tech     No    60.00        Mkt&Fin  61.87  Not Placed
 30   Comm&Mgmt     No    52.00         Mkt&HR  56.70      Placed
 186  Comm&Mgmt     No    55.00        Mkt&Fin  62.93  Not Placed
 9    Comm&Mgmt     No    54.00        Mkt&Fin  52.21  Not Placed
 67   Comm&Mgmt     No    68.71        Mkt&Fin  60.99      Placed
 175   Sci&Tech     No    87.50         Mkt&HR  60.69  Not Placed
 171  Comm&Mgmt    Yes    63.79        Mkt&Fin  66.04      Placed
 18   Comm&Mgmt     No    68.00         Mkt&HR  64.08  Not Placed
 153   Sci&Tech    Yes    86.00        Mkt&Fin  62.48      Placed
 66   Comm&Mgmt     No    68.92         Mkt&HR  58.46      Placed
 185     Others     No    82.00         Mkt&HR  71.43      Placed
 142   Sci&Tech    Yes    60.00        Mkt&Fin  61.29      Placed
 79    Sci&Tech     No    75.00         Mkt&HR  67.99  Not Placed
 25   Comm&Mgmt    Yes    76.00        Mkt&Fin  65.33  Not Placed
 104  Comm&Mgmt    Yes    55.00         Mkt&HR  58.23      Placed
 145   Sci&Tech     No    72.00         Mkt&HR  63.23      Placed
 189  Comm&Mgmt     No    95.65        Mkt&Fin  66.94  Not Placed
 16   Comm&Mgmt    Yes    60.00        Mkt&Fin  62.54      Placed
 45    Sci&Tech     No    58.00         Mkt&HR  66.53  Not Placed
 150   Sci&Tech    Yes    56.00        Mkt&Fin  61.30      Placed
 108  Comm&Mgmt     No    84.00        Mkt&Fin  58.31      Placed
 55   Comm&Mgmt     No    71.00         Mkt&HR  52.71      Placed
 112  Comm&Mgmt     No    58.00         Mkt&HR  53.94      Placed
 191  Comm&Mgmt     No    72.00        Mkt&Fin  61.01      Placed
 124     Others    Yes    64.00         Mkt&HR  61.26      Placed
 128   Sci&Tech    Yes    81.20         Mkt&HR  76.26      Placed
 75   Comm&Mgmt     No    74.00         Mkt&HR  67.00  Not Placed
 135  Comm&Mgmt     No    55.60         Mkt&HR  65.63      Placed
 118   Sci&Tech    Yes    97.00         Mkt&HR  70.48      Placed
 98   Comm&Mgmt     No    70.00        Mkt&Fin  57.31      Placed
 96   Comm&Mgmt    Yes    66.00        Mkt&Fin  64.44      Placed
 183  Comm&Mgmt     No    60.00         Mkt&HR  61.82      Placed
 117   Sci&Tech     No    80.00        Mkt&Fin  67.05      Placed  ,
 93          NaN
 84     300000.0
 95     420000.0
 137    225000.0
 210    400000.0
          ...
 106         NaN
 14          NaN
 92     230000.0
 179         NaN
 102    300000.0
 Name: salary, Length: 172, dtype: float64,
 200    300000.0
 212    295000.0
 138    250000.0
 176    220000.0
 15     200000.0
 111         NaN
 168         NaN
 73     218000.0
 204    210000.0
 139    220000.0
 158         NaN
 30     250000.0
 186         NaN
 9           NaN
 67     275000.0
 175         NaN
 171    290000.0
 18          NaN
 153    340000.0
 66     275000.0
 185    252000.0
 142    260000.0
 79          NaN
 25          NaN
 104    360000.0
 145    400000.0
 189         NaN
 16     300000.0
 45          NaN
 150    690000.0
 108    300000.0
 55     220000.0
 112    250000.0
 191    264000.0
 124    250000.0
 128    400000.0
 75          NaN
 135    200000.0
 118    276000.0
 98     220000.0
 96     300000.0
 183    276000.0
 117    240000.0
 Name: salary, dtype: float64]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#80% of data will be used for training and 20% of data will be used for testing.

In [14]:
X_train

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
93,94,M,52.00,Central,62.0,Central,Commerce,54.0,Comm&Mgmt,No,72.00,Mkt&HR,55.41,Not Placed
84,85,M,70.00,Central,63.0,Others,Science,70.0,Sci&Tech,Yes,55.00,Mkt&Fin,62.00,Placed
95,96,M,73.00,Central,78.0,Others,Commerce,65.0,Comm&Mgmt,Yes,95.46,Mkt&Fin,62.16,Placed
137,138,M,67.00,Others,63.0,Central,Commerce,72.0,Comm&Mgmt,No,56.00,Mkt&HR,60.41,Placed
210,211,M,80.60,Others,82.0,Others,Commerce,77.6,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,M,61.08,Others,50.0,Others,Science,54.0,Sci&Tech,No,71.00,Mkt&Fin,65.69,Not Placed
14,15,M,62.00,Central,47.0,Central,Commerce,50.0,Comm&Mgmt,No,76.00,Mkt&HR,54.96,Not Placed
92,93,F,60.23,Central,69.0,Central,Science,66.0,Comm&Mgmt,No,72.00,Mkt&Fin,59.47,Placed
179,180,F,77.80,Central,64.0,Central,Science,64.2,Sci&Tech,No,75.50,Mkt&HR,72.14,Not Placed
102,103,F,77.00,Others,61.0,Others,Commerce,68.0,Comm&Mgmt,Yes,57.50,Mkt&Fin,61.31,Placed

In [15]:
y_train

93          NaN
84     300000.0
95     420000.0
137    225000.0
210    400000.0
         ...
106         NaN
14          NaN
92     230000.0
179         NaN
102    300000.0
Name: salary, Length: 172, dtype: float64